### ISSUE TITLE
Error when running the code

### ISSUE THREAD

**Issue by dakshanand** [ShangtongZhang/DeepRL#37]
When i run the code for dqn_atari, I get the following error by python examples.py-
```
  File "examples.py", line 423, in <module>
    dqn_cart_pole()
  File "examples.py", line 15, in dqn_cart_pole
    config.evaluation_env = config.task_fn()
  File "examples.py", line 14, in <lambda>
    config.task_fn = lambda: ClassicalControl(game, max_steps=200)
  File "/home/daksh/DeepRL/deep_rl/component/task.py", line 35, in __init__
    BaseTask.__init__(self)
AttributeError: class BaseTask has no attribute '__init__'
```
I tried adding an init function to that class and then it gives a segfault. 
I have all requirements satisfied as given in requirements.txt

**Comment by ShangtongZhang** [comment]
Are you using python 2 or python 3?

**Comment by ShangtongZhang** [comment]
I added a fix and tested in python 2, it should work now.

**Comment by dakshanand** [comment]
I am still getting a segfault with python 2.
As I had written in the first comment too, I had already tried adding an init and after that it gives segfault.

**Comment by ShangtongZhang** [comment]
I have no ideas what's going on. It works well in my Python 2.7 in macOS. I recommend you to use Python3, support for python 2.7 will be removed soon. Docker is also a good choice.
